### ISSUE TITLE
Setting up Kanban

### ISSUE THREAD

**Issue by Abdona** [Abdona/TheMovieHub#21]
Project Link: https://github.com/Abdona/Kanban_Project/projects/2

This Project is developed by:
1. [Abdulrahman Naser](https://github.com/Abdona)
2. [Mwila Kaunda ](https://github.com/softwareengineermwi)

**Comment by abruzy** [comment]
Hi @Abdona & @softwareengineermwi 👋🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚢 
Congratulations! 🎉 

_[OPTIONAL]_

- I have attached a screenshot for a better approach.

<img width="554" alt="Screenshot 2021-08-02 at 12 01 56" src="https://user-images.githubusercontent.com/34798898/127868453-fe9ed76e-cf33-49e3-a6d6-eaa4a0a37713.png">

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Abdona** [comment]
@abruzy Thank you for the review , and for the Optional change request , it was helpful .

**Comment by abruzy** [comment]
Hello @Abdona & @softwareengineermwi!

I've just realized that the issue should use a circle with the user's avatar on each card is required in this project.
I am sorry that you'll have to do another extra work to fix this but please note that I'm human just like you and can make mistakes. I haven't done that on purpose 😊 

I believe that this is a simple fix and shouldn't take much time but I'm willing to help you in case you need me.
All you need is for your card to display each user's avatar. Please check the screenshot below

This is correct look
<img width="396" alt="Screenshot 2021-08-04 at 12 27 38" src="https://user-images.githubusercontent.com/34798898/128173753-111ab45b-8361-49b4-889f-59223e78fed0.png">

And this is how yours look like at the moment
<img width="373" alt="Screenshot 2021-08-04 at 12 33 57" src="https://user-images.githubusercontent.com/34798898/128173964-94fa4352-ed5f-4b28-9a0b-b2d9b0557087.png">

Also, I notice you created a custom column for Student A-Todo and Student B-Todo, you don't need to create a separate column for each student, you only need one column for `Todo`

Please check the screenshot below for the proper way to do it

<img width="1508" alt="Screenshot 2021-08-04 at 12 38 21" src="https://user-images.githubusercontent.com/34798898/128174742-a0e06ab5-57cf-474e-85e5-8dd4d2b58cc7.png">

And this is how yours currently looks like at the moment, please change that to look like the one above

<img width="1474" alt="Screenshot 2021-08-04 at 12 41 59" src="https://user-images.githubusercontent.com/34798898/128174966-d100e27b-c776-443e-8ca0-395d10642214.png">

All you need to do is change Student A-Todo(Abdulrahman) and Student B-Todo(Mwila) to just one column `To do` and also add the `In review` column as well, check the screenshot above to see the correct way of doing it.

Once again, I'm sorry for causing these troubles to you, I'm willing to help you out with this.

**Comment by Abdona** [comment]
Thank you @abruzy .
I have the made all the Changees.
Kindly Check it again.

**Comment by abruzy** [comment]
Great work team 🚀 

Your project is approved, you can proceed to the next step.

Cheers

Happy Coding

**Comment by nidalaa** [comment]
@Abdona and a quick hint from me: if you need a clear view of only your tasks you can use filters like here https://github.com/Abdona/Kanban_Project/projects/2?card_filter_query=assignee%3Aabdona.

That will be even more handy than custom columns :)

**Comment by Abdona** [comment]
@nidalaa This is so much helpful.
it saves a lot of time looking through all the tasks :smile: 
Thank you .
